### ISSUE TITLE
What about REMS? What about sizes?

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/best-practices#6] opened 2016-03-18 15:23 UTC
This morning in our Dare Dev meeting, we talked about consolidating some of our practices around sizing units in our CSS. Here's a brief overview with where we're at:

Since F&M, I have personally been using a set of mix-ins that provide the browser fallbacks for using the `rem` unit:

``` less
// Mixin (assuming a 10px font-size on the html element)
.width(2);

// Result
width: 20px;
width: 2rem
```

The assumption was that this would allow us to scale the entire design system up and down as needed (maybe a client wants to scale the whole thing up?). This was largely playing to an edge case, but on reading further, it seems like a lot of designers and front-end developers out there were relying on `rem` sizing specifically for text sizing so that they could scale things up and down at different break points. We just weren't doing this at all, basically rendering the one good use of rems.

After reading a few articles, [this one in particular](https://mindtheshift.wordpress.com/2015/04/02/r-i-p-rem-viva-css-reference-pixel/), I'm fairly convinced that we can safely move away from the `rem` unit, but @austinstarin is helping me dig up any current accessiblity arguments in favor or `rems`. The long and short of the above article is _browsers no longer jack the user agent's base font-size to fake zoom: they just zoom_. This makes our life easier, and we can just use pixels.

So, I think means we move to what @colpanik and @jth- were noting this morning: define some pixel sizes in your project and represent them through LESS variables. We might have a `_sizes.less` file that looks something like this:

``` less
@size-1: 10px;
@size-2: 22px;
@size-3: 35px;
```

Arguably, it should go in the `utilities` directory so that it gets higher in the order chain (somewhere at the same level as breakpoints).

Thoughts?
cc/ @suhmantha1 @boutell @kyjoya @mcoppola

**Comment by austinstarin** [comment] 2016-03-20 13:15
The W3C's standard found in WCAG 2.0 (Web Content Accessibility Guideline) recommends using ems or percentages for sizing text: https://www.w3.org/WAI/WCAG20/quickref/?showtechniques=144&currentsidebar=%23col_overview#visual-audio-contrast-scale

I did some quick testing in Chrome and Firefox and relative type size units do allow the browser to scale type appropriately when user preferences determine type size (i.e. setting font size to large under Chrome preferences).

If type is set with pixel values—even on the body or html elements—the browser isn't able to adjust a type scale from user settings.

**Comment by jsumnersmith** [comment] 2016-03-22 12:46
So, I guess this leaves us with REMS as the best unit to use for accessibility reasons? Anyone have strong thoughts on that?

**Comment by jth-** [comment] 2016-03-22 14:07
My only question would be if it makes sense to use rem for everything, or
just text, since that's the only place that it seems to be an accessibility
concern.

**Comment by jsumnersmith** [comment] 2016-03-22 14:39
I think that ends up being more of a design questions, so we should probably
build a few test cases to see what the design teams generally thinks before we
make a final decision.

> On Mar 22 2016, at 7:14 am, Jimmy Harrison &lt;notifications@github.com&gt;
wrote:  
My only question would be if it makes sense to use rem for everything, or  
just text, since that's the only place that it seems to be an accessibility  
concern.  
  
On Tue, Mar 22, 2016 at 8:46 AM Joel Smith &lt;notifications@github.com&gt;
wrote:  
  
&gt; So, I guess this leaves us with REMS as the best unit to use for  
&gt; accessibility reasons? Anyone have strong thoughts on that?  
&gt;  
&gt; —  
&gt; You are receiving this because you were mentioned.  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/punkave/best-
practices/issues/6#issuecomment-199795060&gt;  
&gt;  

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/punkave
/best-practices/issues/6#issuecomment-199830843)![](https://github.com/notific
ations/beacon/ABkGkcO8lNFCV7Ra31iPHbcDzvwbR5J8ks5pv_eJgaJpZM4Hz9BJ.gif)

**Comment by austinstarin** [comment] 2016-03-30 20:19
The accessibility concerns go beyond sizing text in relative units. WCAG recommends sizing text containers as well. A few of the recommendations can be found here, including using "liquid layout" or ems to size containers https://www.w3.org/WAI/WCAG20/quickref/?showtechniques=144&currentsidebar=%23col_overview#visual-audio-contrast-scale

My suggestion would be to use a relative unit to size everything (especially text sizes and line-height). Pixel values do however make sense in a few areas like setting `max-width`. On any old projects that use px values I would suggest sticking with that unit for consistency.

**Comment by austinstarin** [comment] 2017-01-13 12:32
Closing this out. Duplicate of #27.

**Closed by austinstarin** 2017-01-13 12:32 UTC
Labels: question
