### ISSUE TITLE
How do I determine breakpoints for a project?

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/best-practices#1] opened 2014-09-09 12:48 UTC
Is there a decent standard that we could all use to create useful breakpoints? Is this something that's too project specific? If general breakpoints are too specific, are there general guidelines that we can follow for determining a set of breakpoints for a project?

**Comment by austinstarin** [comment] 2017-01-13 12:31
Closing this out. Duplicate of #29.

**Closed by austinstarin** 2017-01-13 12:31 UTC
Labels: question
